### ISSUE TITLE
Feedback on week 9 project progress

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#13]
Subject: feedback on week 9 project progress

See [v1.2 progress guide](https://nuscs2113-ay1819s2.github.io/website/admin/project-w09-v12.html) for more details of the activities mentioned below.

### Follow up from v1.1

- [ ]  Auto-publishing set up for the team repo and the website is available at None (:exclamation: try to do by next milestone)
* README page:
     -  [x]  Parts not related to your product are removed (:heavy_check_mark: well done!)
     -  [x]  se-edu/addressbook-level[3/4] acknowledged (:heavy_check_mark: well done!)
     -  [x]  `Ui.png` has been updated (:heavy_check_mark: well done!)

### Recommended progress for v1.2

-  [x]  Issue labels<sup>*</sup> set up e.g., `type.*` and `priority.*` (:heavy_check_mark: well done!)
-  [ ]  All milestones `v1.2`, `v1.3`, `v1.4`, created (:exclamation: try to do by next milestone)
-  [x]  Issues marked as `type.Story` e.g., [link](https://github.com/cs2113-ay1819s2-t08-2/main/issues/1) (:heavy_check_mark: well done!)
-  [x]  Some issues prioritized using `priority.*` labels e.g., [link](https://github.com/cs2113-ay1819s2-t08-2/main/issues/1) (:heavy_check_mark: well done!)
*  Milestone v1.2 _managed_ systematically
     -  [x]  A suitable deadline<sup>**</sup> set (:heavy_check_mark: well done!)
     -  [x]  Issues allocated to v1.2 e.g., [link](https://github.com/cs2113-ay1819s2-t08-2/main/issues/1) (:heavy_check_mark: well done!) 
     -  [x]  All issues/PRs in it are closed/merged  (:heavy_check_mark: well done!) 
     -  [ ]  Milestone closed (:exclamation: try to do by next milestone) 
     -  [ ]  Code tagged as `v1.2` (:exclamation: try to do by next milestone) 
-  [ ]  Build passing [link](nan) (:exclamation: try to do by next milestone)
-  [x]  Some issues assigned to milestone v1.3 e.g., [link](https://github.com/cs2113-ay1819s2-t08-2/main/issues/2) (:heavy_check_mark: well done!)

 <sup>*</sup>Remember to use the format specified, else it will not be picked up by the bot
<sup>**</sup>Remember that the deadline is the midnight before your tutorials

Not graded:
- [x] Updated User Guide for v1.2  (:+1:  Kudos!)

### Follow up from v1.1

* Used forking workflow:
     -  [ ]  Created PRs  (:exclamation: try to do by next milestone)
     -  [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)

- [ ]  Merged updates to documents (:exclamation: try to do by next milestone)
- [ ]  `weizhonglauw.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:exclamation: try to do by next milestone)

### Recommended progress for v1.2

  - [ ]  Merged updates to java/fxml files (:exclamation: try to do by next milestone)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [ ]  Has issues/PRs assigned for the milestone (:exclamation: try to do by next milestone)

### Follow up from v1.1

* Used forking workflow:
     -  [x]  Created PRs [link](https://github.com/cs2113-ay1819s2-t08-2/main/pull/4) (:heavy_check_mark: well done!)
     -  [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)

- [ ]  Merged updates to documents (:exclamation: try to do by next milestone)
- [ ]  `yongjia96.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:exclamation: try to do by next milestone)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [ ]  Has issues/PRs assigned for the milestone (:exclamation: try to do by next milestone)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

### Follow up from v1.1

* Used forking workflow:
     -  [ ]  Created PRs  (:exclamation: try to do by next milestone)
     -  [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)

- [ ]  Merged updates to documents (:exclamation: try to do by next milestone)
- [ ]  `wongyuqi.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:exclamation: try to do by next milestone)

### Recommended progress for v1.2

  - [ ]  Merged updates to java/fxml files (:exclamation: try to do by next milestone)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [ ]  Has issues/PRs assigned for the milestone (:exclamation: try to do by next milestone)

Tutor: @RubaP

Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-03-19 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.
